# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: BoxOfCereal/Granite-tomb-records
  branch: main
  identity_url: https://auth.decapbridge.com/sites/7deae718-ed08-41ba-89c4-9ae82175b993
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://6803a316d0758b0008e05c43--papaya-choux-523d7b.netlify.app

media_folder: src/imgs
public_folder: /imgs

collections:
  - name: "posters"
    label: "Poster Images"
    folder: "src/imgs/posters"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['order', 'title', 'date']
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Poster Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "live_photos"
    label: "Live Photos"
    folder: "src/imgs/live"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['order', 'title']
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "bands"
    label: "Bands"
    folder: "src/bands"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Band Name", name: "name", widget: "string" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Profile Image", name: "profileImage", widget: "image" }
      - { label: "About", name: "about", widget: "text", required: false }
      - label: "Social"
        name: "social"
        widget: "object"
        fields:
          - { label: "Website", name: "website", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "TikTok", name: "tiktok", widget: "string", required: false }
          - { label: "Bluesky", name: "bluesky", widget: "string", required: false }
          - { label: "Bandcamp", name: "bandcamp", widget: "string", required: false }

  - name: "videos"
    label: "Videos"
    folder: "src/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "YouTube ID", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "string" }

  - name: "youtube_playlists"
    label: "YouTube Playlists"
    widget: "list"
    field:
      label: "Playlist URL"
      name: "url"
      widget: "string"